[package]
name    = "tools"
version = "0.1.0"
authors = ["Michal Nazarewicz <mina86@mina86.com>"]
publish = false
edition = "2018"

[dependencies]
delta_e = "^0.2"
# delta_e uses lab 0.7 so we cannot go up to 0.8
# https://github.com/elliotekj/DeltaE/pull/5
lab = "^0.7"
